# Generated by Django 6.0 on 2025-12-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(default='anonymous@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
