# Generated by Django 6.0 on 2025-12-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_content_info_message_rename_title_info_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='message',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='info',
            name='email',
        ),
    ]
