# Generated by Django 6.0 on 2025-12-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_message_info_details_remove_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='class_code',
            field=models.CharField(default='BSIT-BT2-101', max_length=50),
        ),
        migrations.AddField(
            model_name='info',
            name='student_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
